/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab6p2_ianbeltrand;

import java.awt.Color;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JColorChooser;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kevin
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        
        DefaultComboBoxModel modelo = (DefaultComboBoxModel)TiposItem.getModel();
        
        modelo.addElement("Sombrero");
        modelo.addElement("Gafas");
        modelo.addElement("Bufanda");
        modelo.addElement("Chaqueta");
        modelo.addElement("Pantalon");
        modelo.addElement("Zapatos");
        
        TiposItem.setModel(modelo);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PinguinoFrame = new javax.swing.JDialog();
        PanelPrincipal = new javax.swing.JTabbedPane();
        ItemsTab = new javax.swing.JToolBar();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        TablaCompraItems = new javax.swing.JTable();
        ComprarItem = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        TableMyItems = new javax.swing.JTable();
        CasasTab = new javax.swing.JToolBar();
        jPanel2 = new javax.swing.JPanel();
        ComprarCasa = new javax.swing.JButton();
        VenderCasa = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        TablaCasasCompra = new javax.swing.JTable();
        MiCasaTab = new javax.swing.JToolBar();
        jPanel3 = new javax.swing.JPanel();
        NombreCasa = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaPufflesCompra = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaMyPuffles = new javax.swing.JTable();
        ComprarPuffle = new javax.swing.JButton();
        JuegosTab = new javax.swing.JToolBar();
        jPanel4 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        PremiumButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        NombrePinguino = new javax.swing.JLabel();
        DineroPinguino = new javax.swing.JLabel();
        AdminFrame = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jToolBar1 = new javax.swing.JToolBar();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        TablaItems = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        NombreItem = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        PrecioItem = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        TiposItem = new javax.swing.JComboBox<>();
        GuardarItem = new javax.swing.JButton();
        jToolBar2 = new javax.swing.JToolBar();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        TablaCasas = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        NombreCasaA = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        SizeCasaA = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        CostoCasaA = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        XcasaA = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        YcasaA = new javax.swing.JTextField();
        GuardarCasaA = new javax.swing.JButton();
        jToolBar3 = new javax.swing.JToolBar();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        TablaPuffles = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        NombrePuffleA = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        ColorPuffleA = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        PrecioPuffleA = new javax.swing.JTextField();
        GuardarPuffleA = new javax.swing.JButton();
        jToolBar4 = new javax.swing.JToolBar();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        TablaJuegos = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        NombreJuegoA = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        CostoJuegoA = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        RecompensaJuegoA = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        PEjuegoA = new javax.swing.JTextField();
        GuardarJuegoA = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Username = new javax.swing.JTextField();
        Password = new javax.swing.JPasswordField();
        LoginButton = new javax.swing.JButton();

        ItemsTab.setRollover(true);

        TablaCompraItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Tipo", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(TablaCompraItems);
        if (TablaCompraItems.getColumnModel().getColumnCount() > 0) {
            TablaCompraItems.getColumnModel().getColumn(0).setResizable(false);
            TablaCompraItems.getColumnModel().getColumn(1).setResizable(false);
            TablaCompraItems.getColumnModel().getColumn(2).setResizable(false);
        }

        ComprarItem.setText("Comprar");
        ComprarItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ComprarItemMouseClicked(evt);
            }
        });

        TableMyItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Tipo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(TableMyItems);
        if (TableMyItems.getColumnModel().getColumnCount() > 0) {
            TableMyItems.getColumnModel().getColumn(0).setResizable(false);
            TableMyItems.getColumnModel().getColumn(1).setResizable(false);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(ComprarItem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(182, 182, 182))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(ComprarItem)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ItemsTab.add(jPanel1);

        PanelPrincipal.addTab("Items", ItemsTab);

        CasasTab.setRollover(true);

        ComprarCasa.setText("Comprar Casa");
        ComprarCasa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ComprarCasaMouseClicked(evt);
            }
        });

        VenderCasa.setText("Vender Casa");
        VenderCasa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VenderCasaMouseClicked(evt);
            }
        });

        TablaCasasCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Size", "Costo", "X", "Y"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(TablaCasasCompra);
        if (TablaCasasCompra.getColumnModel().getColumnCount() > 0) {
            TablaCasasCompra.getColumnModel().getColumn(0).setResizable(false);
            TablaCasasCompra.getColumnModel().getColumn(1).setResizable(false);
            TablaCasasCompra.getColumnModel().getColumn(2).setResizable(false);
            TablaCasasCompra.getColumnModel().getColumn(3).setResizable(false);
            TablaCasasCompra.getColumnModel().getColumn(4).setResizable(false);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(ComprarCasa)
                        .addGap(50, 50, 50)
                        .addComponent(VenderCasa)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComprarCasa)
                    .addComponent(VenderCasa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        CasasTab.add(jPanel2);

        PanelPrincipal.addTab("Casas", CasasTab);

        MiCasaTab.setRollover(true);

        NombreCasa.setText("jLabel5");

        TablaPufflesCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Color", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TablaPufflesCompra);

        TablaMyPuffles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Color"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(TablaMyPuffles);

        ComprarPuffle.setText("Comprar");
        ComprarPuffle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ComprarPuffleMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(NombreCasa)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(ComprarPuffle)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(NombreCasa)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                        .addComponent(ComprarPuffle)
                        .addGap(109, 109, 109))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        MiCasaTab.add(jPanel3);

        PanelPrincipal.addTab("Mi Casa", MiCasaTab);

        JuegosTab.setRollover(true);

        jButton5.setText("Play");

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Costo", "Recompensa"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable5);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        JuegosTab.add(jPanel4);

        PanelPrincipal.addTab("Juegos", JuegosTab);

        PremiumButton.setText("¡¡¡PREMIUM!!!");

        jLabel4.setFont(new java.awt.Font("MV Boli", 1, 36)); // NOI18N
        jLabel4.setText("CLUB PENGUIN");

        NombrePinguino.setText("Nombre: ");
        NombrePinguino.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                NombrePinguinoPropertyChange(evt);
            }
        });

        DineroPinguino.setText("Dinero: ");

        javax.swing.GroupLayout PinguinoFrameLayout = new javax.swing.GroupLayout(PinguinoFrame.getContentPane());
        PinguinoFrame.getContentPane().setLayout(PinguinoFrameLayout);
        PinguinoFrameLayout.setHorizontalGroup(
            PinguinoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PinguinoFrameLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PremiumButton)
                .addGap(29, 29, 29))
            .addGroup(PinguinoFrameLayout.createSequentialGroup()
                .addGroup(PinguinoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PinguinoFrameLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(PanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PinguinoFrameLayout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PinguinoFrameLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(NombrePinguino)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DineroPinguino)
                .addGap(38, 38, 38))
        );
        PinguinoFrameLayout.setVerticalGroup(
            PinguinoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PinguinoFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(PinguinoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NombrePinguino)
                    .addComponent(DineroPinguino))
                .addGap(18, 18, 18)
                .addComponent(PanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PremiumButton)
                .addContainerGap())
        );

        jLabel7.setFont(new java.awt.Font("MV Boli", 1, 36)); // NOI18N
        jLabel7.setText("ADMINISTRADOR");

        jToolBar1.setRollover(true);

        TablaItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Tipo", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane7.setViewportView(TablaItems);
        if (TablaItems.getColumnModel().getColumnCount() > 0) {
            TablaItems.getColumnModel().getColumn(0).setResizable(false);
        }

        jLabel8.setText("Nombre");

        jLabel9.setText("Precio");

        jLabel10.setText("Tipo");

        GuardarItem.setText("Guardar");
        GuardarItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GuardarItemMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8)
                    .addComponent(NombreItem)
                    .addComponent(jLabel9)
                    .addComponent(PrecioItem)
                    .addComponent(jLabel10)
                    .addComponent(TiposItem, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(GuardarItem, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NombreItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PrecioItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TiposItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(GuardarItem)))
                .addContainerGap(130, Short.MAX_VALUE))
        );

        jToolBar1.add(jPanel5);

        jTabbedPane1.addTab("ITEMS", jToolBar1);

        jToolBar2.setRollover(true);

        TablaCasas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Size", "Costo", "X", "Y"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane8.setViewportView(TablaCasas);
        if (TablaCasas.getColumnModel().getColumnCount() > 0) {
            TablaCasas.getColumnModel().getColumn(0).setResizable(false);
            TablaCasas.getColumnModel().getColumn(1).setResizable(false);
            TablaCasas.getColumnModel().getColumn(2).setResizable(false);
            TablaCasas.getColumnModel().getColumn(3).setResizable(false);
            TablaCasas.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel11.setText("Nombre");

        NombreCasaA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreCasaAActionPerformed(evt);
            }
        });

        jLabel12.setText("Size");

        jLabel13.setText("Costo");

        jLabel14.setText("Coordenada X");

        jLabel15.setText("Coordenada Y");

        GuardarCasaA.setText("Guardar");
        GuardarCasaA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GuardarCasaAMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(XcasaA, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(NombreCasaA))
                            .addComponent(jLabel14))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(YcasaA)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(SizeCasaA, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(25, 25, 25)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel13)
                                    .addComponent(CostoCasaA)
                                    .addComponent(GuardarCasaA, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))))))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NombreCasaA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SizeCasaA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CostoCasaA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(XcasaA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(YcasaA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GuardarCasaA))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jToolBar2.add(jPanel6);

        jTabbedPane1.addTab("CASAS", jToolBar2);

        jToolBar3.setRollover(true);

        TablaPuffles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Color", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane9.setViewportView(TablaPuffles);
        if (TablaPuffles.getColumnModel().getColumnCount() > 0) {
            TablaPuffles.getColumnModel().getColumn(0).setResizable(false);
            TablaPuffles.getColumnModel().getColumn(1).setResizable(false);
            TablaPuffles.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel16.setText("Nombre");

        jLabel17.setText("Color");

        ColorPuffleA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ColorPuffleAMouseClicked(evt);
            }
        });

        jLabel18.setText("Precio");

        GuardarPuffleA.setText("Guardar");
        GuardarPuffleA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GuardarPuffleAMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel16)
                    .addComponent(NombrePuffleA)
                    .addComponent(jLabel17)
                    .addComponent(ColorPuffleA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel18)
                    .addComponent(PrecioPuffleA)
                    .addComponent(GuardarPuffleA, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NombrePuffleA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ColorPuffleA, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PrecioPuffleA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(GuardarPuffleA))
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(92, Short.MAX_VALUE))
        );

        jToolBar3.add(jPanel7);

        jTabbedPane1.addTab("PUFFLES", jToolBar3);

        jToolBar4.setRollover(true);

        TablaJuegos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Costo", "Recompensa", "Porcentaje"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane10.setViewportView(TablaJuegos);
        if (TablaJuegos.getColumnModel().getColumnCount() > 0) {
            TablaJuegos.getColumnModel().getColumn(0).setResizable(false);
            TablaJuegos.getColumnModel().getColumn(1).setResizable(false);
            TablaJuegos.getColumnModel().getColumn(2).setResizable(false);
            TablaJuegos.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel19.setText("Nombre");

        jLabel20.setText("Costo");

        jLabel21.setText("Recompensa");

        jLabel22.setText("Probabilidad de Exito");

        GuardarJuegoA.setText("Guardar");
        GuardarJuegoA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GuardarJuegoAMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel19)
                    .addComponent(NombreJuegoA)
                    .addComponent(jLabel20)
                    .addComponent(CostoJuegoA)
                    .addComponent(jLabel21)
                    .addComponent(RecompensaJuegoA)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(PEjuegoA)
                    .addComponent(GuardarJuegoA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NombreJuegoA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CostoJuegoA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RecompensaJuegoA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PEjuegoA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(GuardarJuegoA)))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        jToolBar4.add(jPanel8);

        jTabbedPane1.addTab("JUEGOS", jToolBar4);

        javax.swing.GroupLayout AdminFrameLayout = new javax.swing.GroupLayout(AdminFrame.getContentPane());
        AdminFrame.getContentPane().setLayout(AdminFrameLayout);
        AdminFrameLayout.setHorizontalGroup(
            AdminFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminFrameLayout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(AdminFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        AdminFrameLayout.setVerticalGroup(
            AdminFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("MV Boli", 0, 36)); // NOI18N
        jLabel1.setText("CLUB PENGUIN");

        jLabel2.setText("Username:");

        jLabel3.setText("Password:");

        Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameActionPerformed(evt);
            }
        });

        LoginButton.setText("LOG IN");
        LoginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginButtonMouseClicked(evt);
            }
        });
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Username)
                            .addComponent(Password)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(148, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(142, 142, 142))
            .addGroup(layout.createSequentialGroup()
                .addGap(245, 245, 245)
                .addComponent(LoginButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(LoginButton)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void NombreCasaAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreCasaAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreCasaAActionPerformed

    private void LoginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginButtonMouseClicked
        // TODO add your handling code here:
        String Name = Username.getText();
        String password = Password.getText();
        
        if(Name.equals("p") && password.equals("p")){
            AdminFrame.setModal(true);
            AdminFrame.pack();
            AdminFrame.setLocationRelativeTo(this);
            AdminFrame.setVisible(true);
        }else{
            if(admi.Buscar(Name, password) != null){
                pinguino = admi.Buscar(Name, password);
                
                String text = NombrePinguino.getText();
                    text = "Nombre: " + this.pinguino.getNombre();
                    NombrePinguino.setText(text);
                    
                    ActualizarDinero();
                    ActualizarTablaItems();
                
                PinguinoFrame.setModal(true);
                PinguinoFrame.pack();
                PinguinoFrame.setLocationRelativeTo(this);
                PinguinoFrame.setVisible(true);
                
            }else{
                if(admi.Buscar(Name, password) == null){
                    Pinguino pinguino = new Pinguino(Name, password);
                    admi.pinguinos.add(pinguino);

                    this.pinguino = admi.Buscar(Name, password);
                
                    String text = NombrePinguino.getText();
                    text = "Nombre: " + this.pinguino.getNombre();
                    NombrePinguino.setText(text);
                    
                    ActualizarDinero();
                    ActualizarTablaItems();
                    
                    PinguinoFrame.setModal(true);
                    PinguinoFrame.pack();
                    PinguinoFrame.setLocationRelativeTo(this);
                    PinguinoFrame.setVisible(true);
                    pinguino = admi.Buscar(Name, password);
                }
            }
        }
    }//GEN-LAST:event_LoginButtonMouseClicked

    private void ActualizarDinero(){
        String textD = DineroPinguino.getText();
        textD = "Dinero: " + pinguino.getDinero();
        DineroPinguino.setText(textD);
    }
    private void GuardarItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuardarItemMouseClicked
        // TODO add your handling code here:
        String Nombre = NombreItem.getText();
        String PrecioS = PrecioItem.getText();
        int Precio = Integer.parseInt(PrecioS);
        String Tipo = TiposItem.getSelectedItem().toString();
        
        Item item = new Item(Nombre, Precio, Tipo);
        admi.items.add(item);
        
        Object[] newrow = {
            item.getNombre(), item.getTipo(), item.getPrecio()
        };
        
        DefaultTableModel modelo = (DefaultTableModel) TablaItems.getModel();
        modelo.addRow(newrow);
        TablaItems.setModel(modelo);
        TablaCompraItems.setModel(modelo);
    }//GEN-LAST:event_GuardarItemMouseClicked

    private void GuardarCasaAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuardarCasaAMouseClicked
        // TODO add your handling code here:
        String Nombre = NombreCasaA.getText();
        String SizeS = SizeCasaA.getText();
        int Size = Integer.parseInt(SizeS);
        String CostoS = CostoCasaA.getText();
        int Costo = Integer.parseInt(CostoS);
        String XS = XcasaA.getText();
        int X = Integer.parseInt(XS);
        String YS = YcasaA.getText();
        int Y = Integer.parseInt(YS);
        
        Casa casa = new Casa(Nombre, Size, Costo, X, Y);
        admi.casas.add(casa);
        
        Object[] newrow = {
            casa.Nombre, casa.getSize(), casa.getCosto(), casa.getCoordenadaX(), casa.getCoordenadaY()
        };
        
        DefaultTableModel modelo = (DefaultTableModel) TablaCasas.getModel();
        modelo.addRow(newrow);
        TablaCasas.setModel(modelo);
        TablaCasasCompra.setModel(modelo);
    }//GEN-LAST:event_GuardarCasaAMouseClicked

    private void ColorPuffleAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ColorPuffleAMouseClicked
        // TODO add your handling code here:
        ColorPuffleA.setBackground(JColorChooser.showDialog(this, "Seleccione el color del Puffle", Color.yellow));
    }//GEN-LAST:event_ColorPuffleAMouseClicked

    private void GuardarPuffleAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuardarPuffleAMouseClicked
        // TODO add your handling code here:
        String Nombre = NombrePuffleA.getText();
        String PrecioS = PrecioPuffleA.getText();
        int Precio = Integer.parseInt(PrecioS);
        Color color = ColorPuffleA.getBackground();
        
        Puffle puffle = new Puffle(Nombre, Precio, color);
        admi.puffles.add(puffle);
        
        Object[] newrow = {
            puffle.getNombre(), puffle.color, puffle.getPrecio()
        };
        
        DefaultTableModel modelo = (DefaultTableModel) TablaPuffles.getModel();
        modelo.addRow(newrow);
        TablaPuffles.setModel(modelo);
        TablaPufflesCompra.setModel(modelo);
    }//GEN-LAST:event_GuardarPuffleAMouseClicked

    private void GuardarJuegoAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuardarJuegoAMouseClicked
        // TODO add your handling code here:
        String Nombre = NombreJuegoA.getText();
        String CostoS = CostoJuegoA.getText();
        int Costo = Integer.parseInt(CostoS);
        String RecompensaS = RecompensaJuegoA.getText();
        int Recompensa = Integer.parseInt(CostoS);
        String PES = PEjuegoA.getText();
        int PE = Integer.parseInt(PES);
        
        Juego juego = new Juego(Nombre, Costo, Recompensa, PE);
        admi.juegos.add(juego);
        
        Object[] newrow = {
            juego.getNombre(), juego.getCosto(), juego.getRecompensa(), juego.getProbabilidadExito()
        };
        
        DefaultTableModel modelo = (DefaultTableModel) TablaJuegos.getModel();
        modelo.addRow(newrow);
        TablaJuegos.setModel(modelo);
    }//GEN-LAST:event_GuardarJuegoAMouseClicked

    private void NombrePinguinoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_NombrePinguinoPropertyChange
        // TODO add your handling code here:
        
    }//GEN-LAST:event_NombrePinguinoPropertyChange

    private void ActualizarTablaItems(){
        DefaultTableModel modelop = (DefaultTableModel) TableMyItems.getModel();
        modelop.setRowCount(0);
        for (Item item : pinguino.getItems()) {
            Object[] newrow = {
                item.getNombre(), item.getTipo()
            };
            modelop.addRow(newrow);
            TableMyItems.setModel(modelop);
        }
    }
    private void ComprarItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ComprarItemMouseClicked
        // TODO add your handling code here:
        if(TablaCompraItems.getSelectedRow() >= 0){
            DefaultTableModel modelo = (DefaultTableModel) TablaCompraItems.getModel();
            
            String Nombre = ((String) modelo.getValueAt(TablaCompraItems.getSelectedRow(), 0));
            String Tipo = ((String) modelo.getValueAt(TablaCompraItems.getSelectedRow(), 1));
            int Precio = ((int) modelo.getValueAt(TablaCompraItems.getSelectedRow(), 2));
            
            if(pinguino.getDinero() >= Precio){
              Item item = new Item(Nombre, Precio, Tipo);
              pinguino.items.add(item);
                admi.items.remove(item);

                ActualizarTablaItems();

                modelo.removeRow(TablaCompraItems.getSelectedRow());
                TablaCompraItems.setModel(modelo);
                TablaItems.setModel(modelo);

                int Dactual = pinguino.getDinero() - Precio;
                pinguino.setDinero(Dactual);
                ActualizarDinero();  
            }
            
        }
    }//GEN-LAST:event_ComprarItemMouseClicked

    private void ActualizarCasa(Casa casa){
        NombreCasa.setText(casa.Nombre);
        
    }
    
    private void ComprarCasaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ComprarCasaMouseClicked
        // TODO add your handling code here:
        if(TablaCasasCompra.getSelectedRow() >= 0){
            DefaultTableModel modelo = (DefaultTableModel) TablaCasas.getModel();
            
            String Nombre = ((String) modelo.getValueAt(TablaCasasCompra.getSelectedRow(), 0));
            int Size = ((int) modelo.getValueAt(TablaCasasCompra.getSelectedRow(), 1));
            int Precio = ((int) modelo.getValueAt(TablaCasasCompra.getSelectedRow(), 2));
            int X = ((int) modelo.getValueAt(TablaCasasCompra.getSelectedRow(), 3));
            int Y = ((int) modelo.getValueAt(TablaCasasCompra.getSelectedRow(), 4));
            
            if(pinguino.getDinero() >= Precio && pinguino.getCasa() == null){
              Casa casa = new Casa(Nombre, Size, Precio, X, Y);
              pinguino.setCasa(casa);
                admi.casas.remove(casa);

                ActualizarCasa(casa);

                modelo.removeRow(TablaCasasCompra.getSelectedRow());
                TablaCasasCompra.setModel(modelo);
                TablaCasas.setModel(modelo);

                int Dactual = pinguino.getDinero() - Precio;
                pinguino.setDinero(Dactual);
                ActualizarDinero();  
            }
            
        }
    }//GEN-LAST:event_ComprarCasaMouseClicked

    private void VenderCasaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VenderCasaMouseClicked
        // TODO add your handling code here:
        if(pinguino.getCasa() != null){
            pinguino.setDinero(pinguino.getDinero() + pinguino.getCasa().getCosto());
            pinguino.setCasa(null);
            NombreCasa.setText("NO TIENES CASA");
            ActualizarDinero();
            DefaultTableModel modelop = (DefaultTableModel) TablaMyPuffles.getModel();
            modelop.setRowCount(0);
        }
        
    }//GEN-LAST:event_VenderCasaMouseClicked

    private void ActualizarTablaPuffles(){
        DefaultTableModel modelop = (DefaultTableModel) TablaMyPuffles.getModel();
        modelop.setRowCount(0);
        for (Puffle puffle : pinguino.casa.getPuffles()) {
            Object[] newrow = {
                puffle.getNombre(), puffle.getColor()
            };
            modelop.addRow(newrow);
            TablaMyPuffles.setModel(modelop);
        }
    }
    
    private void ComprarPuffleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ComprarPuffleMouseClicked
        // TODO add your handling code here:
        if(TablaPufflesCompra.getSelectedRow() >= 0){
            DefaultTableModel modelo = (DefaultTableModel) TablaPufflesCompra.getModel();
            
            String Nombre = ((String) modelo.getValueAt(TablaPufflesCompra.getSelectedRow(), 0));
            Color color = ((Color) modelo.getValueAt(TablaPufflesCompra.getSelectedRow(), 1));
            int Precio = ((int) modelo.getValueAt(TablaPufflesCompra.getSelectedRow(), 2));
            
            if(pinguino.getDinero() >= Precio){
              Puffle puffle = new Puffle(Nombre, Precio, color);
              pinguino.casa.puffles.add(puffle);
                admi.puffles.remove(puffle);

                ActualizarTablaPuffles();

                modelo.removeRow(TablaPufflesCompra.getSelectedRow());
                TablaPufflesCompra.setModel(modelo);
                TablaPuffles.setModel(modelo);

                int Dactual = pinguino.getDinero() - Precio;
                pinguino.setDinero(Dactual);
                ActualizarDinero();  
            }
            
        }
    }//GEN-LAST:event_ComprarPuffleMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog AdminFrame;
    private javax.swing.JToolBar CasasTab;
    private javax.swing.JButton ColorPuffleA;
    private javax.swing.JButton ComprarCasa;
    private javax.swing.JButton ComprarItem;
    private javax.swing.JButton ComprarPuffle;
    private javax.swing.JTextField CostoCasaA;
    private javax.swing.JTextField CostoJuegoA;
    private javax.swing.JLabel DineroPinguino;
    private javax.swing.JButton GuardarCasaA;
    private javax.swing.JButton GuardarItem;
    private javax.swing.JButton GuardarJuegoA;
    private javax.swing.JButton GuardarPuffleA;
    private javax.swing.JToolBar ItemsTab;
    private javax.swing.JToolBar JuegosTab;
    private javax.swing.JButton LoginButton;
    private javax.swing.JToolBar MiCasaTab;
    private javax.swing.JLabel NombreCasa;
    private javax.swing.JTextField NombreCasaA;
    private javax.swing.JTextField NombreItem;
    private javax.swing.JTextField NombreJuegoA;
    private javax.swing.JLabel NombrePinguino;
    private javax.swing.JTextField NombrePuffleA;
    private javax.swing.JTextField PEjuegoA;
    private javax.swing.JTabbedPane PanelPrincipal;
    private javax.swing.JPasswordField Password;
    private javax.swing.JDialog PinguinoFrame;
    private javax.swing.JTextField PrecioItem;
    private javax.swing.JTextField PrecioPuffleA;
    private javax.swing.JButton PremiumButton;
    private javax.swing.JTextField RecompensaJuegoA;
    private javax.swing.JTextField SizeCasaA;
    private javax.swing.JTable TablaCasas;
    private javax.swing.JTable TablaCasasCompra;
    private javax.swing.JTable TablaCompraItems;
    private javax.swing.JTable TablaItems;
    private javax.swing.JTable TablaJuegos;
    private javax.swing.JTable TablaMyPuffles;
    private javax.swing.JTable TablaPuffles;
    private javax.swing.JTable TablaPufflesCompra;
    private javax.swing.JTable TableMyItems;
    private javax.swing.JComboBox<String> TiposItem;
    private javax.swing.JTextField Username;
    private javax.swing.JButton VenderCasa;
    private javax.swing.JTextField XcasaA;
    private javax.swing.JTextField YcasaA;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable5;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JToolBar jToolBar3;
    private javax.swing.JToolBar jToolBar4;
    // End of variables declaration//GEN-END:variables
    Admi admi = new Admi();
    Pinguino pinguino = null;

}
